name: "Continuos Integration (CI) Install dependesse"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Dependesse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Install dependesse
        run: yarn 
